services:
  - type: web
    name: cinemate
    env: docker
    buildCommand: docker build -f ./docker/8.3/Dockerfile --build-arg WWWGROUP='${WWWGROUP}' -t sail-8.3/app .
    startCommand: docker run -d -p '${APP_PORT:-80}:80' -p '${VITE_PORT:-5173}:${VITE_PORT:-5173}' -e WWWUSER='${WWWUSER}' -e LARAVEL_SAIL=1 -e XDEBUG_MODE='${SAIL_XDEBUG_MODE:-off}' -e XDEBUG_CONFIG='${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}' -e IGNITION_LOCAL_SITES_PATH='${PWD}' -v '.:/var/www/html' --network sail sail-8.3/app
    envVars:
      - key: WWWGROUP
        value: '${WWWGROUP}'
      - key: WWWUSER
        value: '${WWWUSER}'
      - key: LARAVEL_SAIL
        value: '1'
      - key: XDEBUG_MODE
        value: '${SAIL_XDEBUG_MODE:-off}'
      - key: XDEBUG_CONFIG
        value: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      - key: IGNITION_LOCAL_SITES_PATH
        value: '${PWD}'
      - key: APP_PORT
        value: '${APP_PORT:-80}'
      - key: VITE_PORT
        value: '${VITE_PORT:-5173}'
    disk:
      - mountPath: '/var/www/html'
        sizeGB: 0.5 # Ajustado para 500MB
